package Concesionaria;
/**
 * @author Prof Matias Garcia.
 * <p> Copyright (C) 2017 para <a href = "https://www.profmatiasgarcia.com.ar/"> www.profmatiasgarcia.com.ar </a>
 * - con licencia GNU GPL3.
 * <p> Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los términos de la
 * Licencia Pública General de GNU según es publicada por la Free Software Foundation, 
 * bien con la versión 3 de dicha Licencia o bien (según su elección) con cualquier versión posterior. 
 * Este programa se distribuye con la esperanza de que sea útil, pero SIN NINGUNA GARANTÍA, 
 * incluso sin la garantía MERCANTIL implícita o sin garantizar la CONVENIENCIA PARA UN PROPÓSITO
 * PARTICULAR. Véase la Licencia Pública General de GNU para más detalles.
 * Debería haber recibido una copia de la Licencia Pública General junto con este programa. 
 * Si no ha sido así ingrese a <a href = "http://www.gnu.org/licenses/"> GNU org </a>
 */
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class VendedoresVentana extends javax.swing.JInternalFrame {

    // Atributo para manejar si hay una ventana abierta de este tipo
    public static boolean abierta = false;

    // Modelo de datos para lista de vendedores
    DefaultListModel modeloVendedores = new DefaultListModel();

    public VendedoresVentana() {

        // Llama al constructor de la superclase y establece las caracteristicas de ventana
        super("Administracion de Vendedores",
                true, //resizable
                true, //closable
                true, //maximizable
                true);//iconifiable

        // Establece en true el atributo abierto representando que hay una ventana de este tipo abierta
        abierta = true;

        // Invoca al metodo initComponents()
        initComponents();

        // Relaciona el modelo de vendedores con la lista de vendedores
        listVendedores.setModel(modeloVendedores);
        
    }

    public void limpiarFormulario() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtDni.setText("");
        txtAutosVendidos.setText("");
    }

    public boolean validarFormulario() {

        // Valida que el nombre no este vacio
        if (txtNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El nombre no puede estar vacio!", "Guardar", JOptionPane.WARNING_MESSAGE);
            txtNombre.requestFocus();
            return false;
        }

        // Valida que el apellido no este vacio
        if (txtApellido.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El apellido no puede estar vacio!", "Guardar", JOptionPane.WARNING_MESSAGE);
            txtApellido.requestFocus();
            return false;
        }

        // Valida que el DNI no este vacio
        if (txtDni.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El DNI no puede estar vacio!", "Guardar", JOptionPane.WARNING_MESSAGE);
            txtDni.requestFocus();
            return false;
        }

        // Valida que la cantidad de autos vendidos no este vacio
        if (txtAutosVendidos.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "La cantidad de autos vendidos no puede estar vacio!", "Guardar", JOptionPane.WARNING_MESSAGE);
            txtAutosVendidos.requestFocus();
            return false;
        }

        // Valida que la cantidad de autos sea un numero entero
        try {
            Integer.parseInt(txtAutosVendidos.getText());
        } catch (Exception NumberFormatException) {
            JOptionPane.showMessageDialog(this, "La cantidad de autos debe ser un numero entero!", "Guardar", JOptionPane.WARNING_MESSAGE);
            txtAutosVendidos.requestFocus();
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listVendedores = new javax.swing.JList();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtAutosVendidos = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JButton();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Vendedores")));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listVendedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listVendedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listVendedores);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 20, 163, 146));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 236, -1, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 236, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 236, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 183, 499, 11));

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 27, -1, -1));

        jLabel2.setText("Apellido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 68, -1, -1));

        jLabel3.setText("Nro Documento");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 109, -1, -1));

        jLabel4.setText("Autos Vendidos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 149, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 24, 186, -1));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 65, 186, -1));
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 106, 186, -1));
        getContentPane().add(txtAutosVendidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 146, 186, -1));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 236, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listVendedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listVendedoresMouseClicked

        // Activa el boton 'eliminar'
        btnEliminar.setEnabled(true);

        // Activa el boton 'guardar'
        btnGuardar.setEnabled(true);

        // Obtiene el item seleccionado
        Vendedor v = (Vendedor) listVendedores.getSelectedValue();

        // Completa las cajas de texto segun el elemento
        txtNombre.setText(v.getNombre());
        txtApellido.setText(v.getApellido());
        txtDni.setText(v.getNumeroDocumento());
        txtAutosVendidos.setText(String.valueOf(v.getCantAutosVendidos()));

    }//GEN-LAST:event_listVendedoresMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        // Si hay un elemento seleccionado, lo elimina
        if (listVendedores.getSelectedIndex() != -1) {

            // Consulta si desea eliminar el item
            int rta = JOptionPane.showConfirmDialog(this,
                    "Desea eliminar al vendedor " + listVendedores.getSelectedValue() + " ?", "Eliminar", JOptionPane.YES_NO_OPTION);

            // Si no desea borrarlo, entonces no lo borra
            if (rta == JOptionPane.NO_OPTION) {
                return;
            }

            // Elimina el vendedor
            modeloVendedores.remove(listVendedores.getSelectedIndex());

            // Deshabilita el boton 'eliminar'
            btnEliminar.setEnabled(false);

            // Deshabilita el boton 'guardar'
            btnGuardar.setEnabled(false);

            // Limpia el formulario
            limpiarFormulario();

            // Informa que el vendedor ha sido eliminado
            JOptionPane.showMessageDialog(this, "El vendedor ha sido eliminado!", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        // Variables
        boolean esNuevo = true;

        // Valida el formulario
        boolean validacionOk = validarFormulario();

        // Si el formulario es valido, informa
        if (validacionOk) {

            // Instancia un vendedor
            Vendedor v = new Vendedor();

            // Si hay un item seleccionado lo obtiene
            if (listVendedores.getSelectedIndex() != -1) {
                v = (Vendedor) listVendedores.getSelectedValue();
                esNuevo = false;
            }

            // Agrega el vendedor a la lista de vendedores
            v.setNombre(txtNombre.getText());
            v.setApellido(txtApellido.getText());
            v.setNumeroDocumento(txtDni.getText());
            v.setCantAutosVendidos(Integer.parseInt(txtAutosVendidos.getText()));

            // Si es un vendedor nuevo lo agrega
            if (esNuevo) {
                modeloVendedores.addElement(v);
            }

            // Limpia el formulario
            limpiarFormulario();

            //  Desactiva boton 'guardar'
            btnGuardar.setEnabled(false);

            //  Desactiva boton 'eliminar'
            btnEliminar.setEnabled(false);

            // Activa boton 'nuevo'
            btnNuevo.setEnabled(true);

            // Establece el foco en el boton 'nuevo'
            btnNuevo.requestFocus();

            // No deja ningun item seleccionado en la lista
            listVendedores.clearSelection();

            // Infoma OK!
            JOptionPane.showMessageDialog(this, "El vendedor ha sido guardado!", "Guardar", JOptionPane.INFORMATION_MESSAGE);

        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        // Limpia las cajas de texto
        limpiarFormulario();

        // Deshabilita boton nuevo
        btnNuevo.setEnabled(false);

        // Deshabilita boton eliminar
        btnEliminar.setEnabled(false);

        // Habilita boton guardar
        btnGuardar.setEnabled(true);

        // Ubica el curso en la primer caja de texto
        txtNombre.requestFocus();

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed

        // Cuando cierra la ventana, establece 'abierto' en falso
        abierta = false;

    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList listVendedores;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtAutosVendidos;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
